covidwatch/urls.py
from django.contrib import admin
from django.urls import path, include

from users.views import register_success
from .views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index),
    path('user/', include('users.urls')),
    path('api/', include('users.urls')),
]

users/urls.py
from django.contrib import admin
from django.urls import path, re_path

from . import views

urlpatterns = [
    # path('login/', views.login, name='user_login'),
    # path('logout/', views.logout, name='user_logout'),
    path('register/', views.register, name='user_register'),
    path('register/success/', views.register_success, name='user_register_success'),
    path('login', views.login, name='api_login'),
    path('upload/tcn/rx', views.upload_tcn_rx, name='api_upload_tcn_rx'),
    path('upload/tcn/tx', views.upload_tcn_tx, name='api_upload_tcn_tx'),
    path('upload/attack/log', views.upload_attack_log, name='api_upload_attack_log'),
    path('update/exp_id', views.update_exp_id, name='api_update_exp_id'),
    path('download', views.apk_download, name='apk_download'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser):
    name = models.CharField(blank=False, null=True, max_length=20)
    phone = models.CharField(blank=False, null=True, max_length=10)
    school = models.CharField(blank=False, null=True, max_length=30)
    token = models.CharField(null=True, max_length=44)
    expire_time = models.DateTimeField(null=True, auto_now=False, auto_now_add=False)
    uuid = models.CharField(null=True, max_length=100)
    last_api_calling = models.DateTimeField(null=True, auto_now=False, auto_now_add=False)

    class Meta(AbstractUser.Meta):
        pass

class TCN_RX(models.Model):
    tx_muuid = models.CharField(max_length=100)
    rx_muuid_short = models.CharField(null=True, max_length=100)
    tx_muuid_short = models.CharField(null=True, max_length=100)
    rx_tcn = models.CharField(max_length=100)
    tcn = models.CharField(max_length=100)
    rssi = models.FloatField()
    distance = models.FloatField()
    unix_timestamp = models.DateTimeField(auto_now=False, auto_now_add=False)
    upload_timestamp = models.DateTimeField(auto_now=False, auto_now_add=False)
    exp_id = models.CharField(null=True, max_length=2)
    latitude = models.FloatField()
    longitude = models.FloatField()
    power = models.FloatField()

class TCN_TX(models.Model):
    tx_muuid_short = models.CharField(null=True, max_length=100)
    tx_muuid = models.CharField(max_length=100)
    tx_tcn = models.CharField(max_length=100)
    own_tcn = models.CharField(max_length=100)
    battery_level = models.IntegerField()
    motion_status = models.BooleanField()
    gps_status = models.BooleanField()
    unix_timestamp = models.DateTimeField(auto_now=False, auto_now_add=False)
    upload_timestamp = models.DateTimeField(auto_now=False, auto_now_add=False)
    exp_id = models.CharField(null=True, max_length=2)
    power = models.IntegerField()

class AttackLog(models.Model):
    blind_log = models.TextField(null=True)
    unix_timestamp = models.DateTimeField(null=True, auto_now=False, auto_now_add=False)

class GlobalSetting(models.Model):
    exp_id = models.CharField(null=True, max_length=2)

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib import auth
from django import forms

from .models import User

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput())

    def clean(self):
        username = self.cleaned_data['username']
        password = self.cleaned_data['password']
        user = auth.authenticate(username=username, password=password)
        if not user:
            raise forms.ValidationError('Incorrect username or password.')
        return self.cleaned_data

    def login(self):
        username = self.cleaned_data['username']
        password = self.cleaned_data['password']
        user = auth.authenticate(username=username, password=password)
        return user

class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate
from django.contrib.auth import login as d_login
from django.http import HttpResponse, JsonResponse, FileResponse
from django.views.decorators.csrf import csrf_exempt
from django.utils import timezone

import json
import secrets
import datetime
import logging

from . import forms
from .models import User, TCN_RX, TCN_TX, AttackLog, GlobalSetting
from covidwatch.settings import OS_LIST

# Create your views here.

logging.basicConfig(
    filename='expid_update_log.txt',
    level=logging.DEBUG,
    format='%(asctime)s - %(levelname)-s: %(message)s'
)

@csrf_exempt
def register(request):
    if request.user.is_authenticated:
        return redirect('/')
    form = forms.RegisterForm(request.POST or None)
    if request.POST and form.is_valid():
        form.save()
        return redirect('user_register_success')
    return render(request, 'register.html', context=locals())

def register_success(request):
    return render(request, 'register_success.html', locals())

@csrf_exempt
def login(request):
    if request.POST:
        username = request.POST.get('username')
        password = request.POST.get('password')
        os = request.POST.get('os')
        version = request.POST.get('version')
        if os == None:
            return JsonResponse({
                'success': False, 
                'message': 'No OS Info'
            })
        if os not in OS_LIST:
            return JsonResponse({
                'success': False, 
                'message': 'Wrong OS'
            })
        uuid = request.POST.get('uuid')
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.uuid is None:
                user.uuid = uuid
                user.save()
            elif user.uuid != uuid:
                return JsonResponse({
                    'success': False, 
                    'message': 'Wrong UUID'
                })
            if OS_LIST[os] != version:
                return JsonResponse({
                    'success': False, 
                    'message': 'Wrong Version with OS'
                })

            d_login(request, user)
            token = secrets.token_urlsafe(32)
            expire_time = datetime.datetime.now() + datetime.timedelta(days=3)
            user.token = token
            user.expire_time = expire_time
            user.last_api_calling = datetime.datetime.now()
            user.save()
            return JsonResponse({
                'success': True, 
                'token': token
            })
        else:
            return JsonResponse({
                'success': False, 
                'message': 'User Not Found'
            })
    return JsonResponse({
        'success': False, 
        'message': 'Wrong Method'
    })

@csrf_exempt
def upload_tcn_rx(request):
    data = json.loads(request.body)
    uuid = data['uuid']
    token = data['token']
    user = User.objects.get(uuid=uuid)
    
    if user.token == token:
        if user.expire_time < datetime.datetime.now():
            return JsonResponse({
                'success': False, 
                'message': 'Token Expired'
            })
        else:
            expire_time = datetime.datetime.now() + datetime.timedelta(days=3)
            user.expire_time = expire_time
            user.save()
    else:
        return JsonResponse({
            'success': False, 
            'message': 'Invalid Token'
        })

    if request.method == 'POST':
        setting = GlobalSetting.objects.get(id=1)
        for record in data['TCN_RX']:
            try:
                tcn_rx = TCN_RX(
                    rx_muuid_short=record['RX_MUUID_SHORT'],
                    tx_muuid_short=record['TX_MUUID_SHORT'],
                    tx_muuid=record['TX_MUUID'],
                    rx_tcn=record['RX_TCN'],
                    tcn=record['TCN'],
                    rssi=record['RSSI'],
                    distance=record['DISTANCE'],
                    unix_timestamp=datetime.datetime.fromtimestamp(record['UNIX_TIMESTAMP']),
                    upload_timestamp=datetime.datetime.now(),
                    exp_id=setting.exp_id,
                    latitude=record['LATITUDE'],
                    longitude=record['LONGITUDE'],
                    power=record['YOUR_IOS_SEND_TX_POWER']
                )
                tcn_rx.save()
            except:
                return JsonResponse({
                    'success': False, 
                    'message': 'Invalid Field or Data'
                })
        user.last_api_calling = datetime.datetime.now()
        user.save()
        return JsonResponse({
            'success': True
        })
    return JsonResponse({
        'success': False, 
        'message': 'Wrong Method'
    })

@csrf_exempt
def upload_tcn_tx(request):
    data = json.loads(request.body)
    uuid = data['uuid']
    token = data['token']
    user = User.objects.get(uuid=uuid)
    
    if user.token == token:
        if user.expire_time < datetime.datetime.now():
            return JsonResponse({
                'success': False, 
                'message': 'Token Expired'
            })
        else:
            expire_time = datetime.datetime.now() + datetime.timedelta(days=3)
            user.expire_time = expire_time
            user.save()
    else:
        return JsonResponse({
            'success': False, 
            'message': 'Invalid Token'
        })

    if request.method == 'POST':
        setting = GlobalSetting.objects.get(id=1)
        for record in data['TCN_TX']:
            try:
                tcn_tx = TCN_TX(
                    tx_muuid_short=record['TX_MUUID_SHORT'],
                    tx_muuid=record['TX_MUUID'],
                    tx_tcn=record['TX_TCN'],
                    own_tcn=record['OWN_TCN'],
                    battery_level=record['BATTERY_LEVEL'],
                    motion_status=record['MOTION_STATUS'],
                    gps_status=record['GPS_STATUS'],
                    unix_timestamp=datetime.datetime.fromtimestamp(record['UNIX_TIMESTAMP']),
                    upload_timestamp=datetime.datetime.now(),
                    exp_id=setting.exp_id,
                    power=record['ANDROID_TX_POWER_LEVEL'],
                )
                tcn_tx.save()
            except:
                return JsonResponse({
                    'success': False, 
                    'message': 'Invalid Field or Data'
                })
        user.last_api_calling = datetime.datetime.now()
        user.save()
        return JsonResponse({
            'success': True
        })
    return JsonResponse({
        'success': False, 
        'message': 'Wrong Method'
    })

@csrf_exempt
def upload_attack_log(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        for record in data:
            try:
                attack = AttackLog(
                    blind_log=record['blindLog'], 
                    unix_timestamp=datetime.datetime.fromtimestamp(record['UNIX_TIMESTAMP'])
                )
                attack.save()
            except:
                return JsonResponse({'success': False})
        return JsonResponse({'success': True})
    return JsonResponse({'success': False})

@csrf_exempt
def update_exp_id(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        exp_id = data['exp_id']
        setting, created = GlobalSetting.objects.get_or_create(id=1)
        setting.exp_id = exp_id
        setting.save()
        logging.info('Update Experiment ID: ' + str(exp_id))
        return JsonResponse({'success': True})
    return JsonResponse({'success': False})

def apk_download(request):
    file = open('static/assets/contact-tracing.apk','rb')
    response = FileResponse(file)
    response['Content-Type'] = 'application/octet-stream'
    response['Content-Disposition'] = 'attachment;filename="contact-tracing.apk"'
    return response

users/templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Register{% endblock title %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-lg-5">
    <div class="card mt-5">
      <div class="card-body">
        <h1 class="card-title text-center">Register</h1>
          {% if form.errors %}
            <div class="alert alert-danger" role="alert">
              <h4>Invalid Input (◐‿◑)</h4>
              <ul>
                {% for field in form %}
                  {% if field.errors %}
                    {% for error in field.errors %}
                      <li>{{ error|escape }}</li>
                    {% endfor %}
                  {% endif %}
                {% endfor %}
              </ul>
              {% if form.non_field_errors %}
                {{ form.non_field_errors }}
              {% endif %}
            </div>
          {% endif %}
          <form action="" method="POST">
            {% csrf_token %}
            <div class="form-group">
              <label for="username" class="text-muted">Username</label>
              <input class="form-control" type="text" name="username" required minlengrh="8" maxlength="20" required="" id="username">
            </div>
            <div class="form-group">
              <label for="id_email" class="text-muted">Email</label>
              <input class="form-control" type="email" name="email" required="" maxlength="254" id="id_email">
            </div>
            <!-- <div class="form-group">
              <label for="id_phone" class="text-muted">Cellphone</label>
              <input class="form-control" type="text" name="phone" minlength="10" maxlength="10" required="" id="id_phone">
            </div>
            <div class="form-group">
              <label for="id_name" class="text-muted">Fullname</label>
              <input class="form-control" type="text" name="name" maxlength="20" required="" id="id_name">
            </div>
            <div class="form-group">
              <label for="id_school" class="text-muted">School</label>
              <input class="form-control" type="text" name="school" maxlength="30" required="" id="id_school">
            </div> -->
            <div class="form-group">
              <label for="id_password1" class="text-muted">Password</label>
              <input class="form-control" type="password" name="password1" autocomplete="new-password" required="" id="id_password1">
            </div>
            <div class="form-group">
              <label for="id_password2" class="text-muted">Confirm Password</label>
              <input class="form-control" type="password" name="password2" autocomplete="new-password" required="" id="id_password2">
            </div>
            {% comment %} {% csrf_token %} {{ form.as_p }} {% endcomment %}
            <button type="submit" class="card-link btn btn-primary">Submit</button>
          </form>
          <div class="mt-5">
            <a href="/api/download">Download APK(Android)</a>
            <br>
            <a href="https://hackmd.io/@klin0114/testflight_howto">iOS app HOW TO</a>
          </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

users/templates/register_success.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Register Success{% endblock title %}
{% block css %}<link rel="stylesheet" href="{% static 'css/index.css' %}">{% endblock css %}

{% block content %}
<div class="row justify-content-center">
  <div class="col-5">
    <div class="alert alert-success mt-5" role="alert">
      Register Success🐛
    </div>
  </div>
</div>
{% endblock content %}